test: report invocation errors
When `object.invoke()` fails, report the error instead of failing on
an assertion that expects that the invocation succeeded.

This makes failure messages incredibly more helpful.

Before:

     Uncaught AssertionError: false == true

After:

    Error: Invalid value for argument 'b' of type 'number': undefined.
    Received type was converted to undefined.