Stop changing read-only Number property
Rework the code defining missing ES5/ES6 Number properties to not touch
the existing properties. This is needed to prevent errors like the
following:

    TypeError: Cannot assign to read only property 'MAX_SAFE_INTEGER'
    of function Number() { [native code] }"]