Fix handling of anonymous object types
In LoopBack, the method `PersistedModel.updateAll` describes the return
type using an inline (anonymous) definition:

  returns: {
    arg: 'info',
    type: {
      count: {
        type: 'number',
        description: 'The number of instances updated',
      },
    },
    root: true,
  },

Before this change, remote invocation of updateAll was crashing the
process with the following error:

  AssertionError: type must be either an array or a string.

This commit fixes the problem as follows:

- A try/catch block is introduced to correctly report any sync errors
  via the callback

- The type registry was improved to recognize anonymous object types
  and use the "object" converter for them.

Signed-off-by: Miroslav Bajtoš <mbajtoss@gmail.com>